
import Models.*;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lokaler Benutzer
 */
public class AngebotsvergleichGUI extends javax.swing.JFrame {
    DBConn db;
    /**
     * Creates new form AngebotsvergleichGUI
     */
    public AngebotsvergleichGUI() {
        initComponents();
        tblProductCompare.getColumnModel().removeColumn(tblProductCompare.getColumn("ID"));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductCompare = new javax.swing.JTable();
        btnCompareProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        paneProduct = new javax.swing.JPanel();
        txtPrProductNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrAmount = new javax.swing.JTextField();
        cbPrCompany = new javax.swing.JComboBox<Company>();
        jLabel8 = new javax.swing.JLabel();
        cbPrMarket = new javax.swing.JComboBox<Market>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneDescription = new javax.swing.JTextArea();
        btAddProduct = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbPrProductType = new javax.swing.JComboBox<ProductType>();
        paneProductType = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPtName = new javax.swing.JTextField();
        btAddProductType = new javax.swing.JButton();
        paneCompany = new javax.swing.JPanel();
        btAddCompany = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        cbCPlace = new javax.swing.JComboBox<Place>();
        jLabel11 = new javax.swing.JLabel();
        paneMarket = new javax.swing.JPanel();
        btAddMarket = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbMPlace = new javax.swing.JComboBox<Place>();
        panePlace = new javax.swing.JPanel();
        btAddPlace = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPlStreet = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPlPLZ = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPlCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSearchTerm = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Angebotsvergleich");

        tblProductCompare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Bezeichnung", "Produktnummer", "Preis", "Markt"
            }
        ));
        jScrollPane1.setViewportView(tblProductCompare);

        btnCompareProduct.setText("vergleichen");
        btnCompareProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCompareProduct))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompareProduct)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Normal-Vergleich", jPanel2);

        jLabel4.setText("Direkter Vergleich");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Direkt-Vergleich", jPanel3);

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });
        jTabbedPane2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane2FocusGained(evt);
            }
        });

        jLabel2.setText("Produktnummer");

        jLabel5.setText("Menge");

        cbPrCompany.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPrCompanyItemStateChanged(evt);
            }
        });

        jLabel8.setText("Hersteller");

        cbPrMarket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPrMarketItemStateChanged(evt);
            }
        });

        jLabel7.setText("Markt");

        jLabel6.setText("Beschreibung");

        txtPaneDescription.setColumns(20);
        txtPaneDescription.setRows(5);
        jScrollPane2.setViewportView(txtPaneDescription);

        btAddProduct.setText("AddData");
        btAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductActionPerformed(evt);
            }
        });

        jLabel17.setText("Produkttyp");


        javax.swing.GroupLayout paneProductLayout = new javax.swing.GroupLayout(paneProduct);
        paneProduct.setLayout(paneProductLayout);
        paneProductLayout.setHorizontalGroup(
            paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneProductLayout.createSequentialGroup()
                        .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneProductLayout.createSequentialGroup()
                                .addComponent(txtPrProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(paneProductLayout.createSequentialGroup()
                                .addComponent(cbPrMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbPrCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(cbPrProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(paneProductLayout.createSequentialGroup()
                        .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneProductLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddProduct)
                .addContainerGap())
        );
        paneProductLayout.setVerticalGroup(
            paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProductLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(paneProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cbPrCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cbPrProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAddProduct)
                .addGap(13, 13, 13))
        );

        jTabbedPane2.addTab("Produkt", paneProduct);

        jLabel9.setText("Name");

        btAddProductType.setText("AddData");
        btAddProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneProductTypeLayout = new javax.swing.GroupLayout(paneProductType);
        paneProductType.setLayout(paneProductTypeLayout);
        paneProductTypeLayout.setHorizontalGroup(
            paneProductTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProductTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPtName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProductTypeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddProductType)
                .addContainerGap())
        );
        paneProductTypeLayout.setVerticalGroup(
            paneProductTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProductTypeLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(paneProductTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btAddProductType)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Produkttyp", paneProductType);

        btAddCompany.setText("AddData");
        btAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCompanyActionPerformed(evt);
            }
        });

        jLabel10.setText("Name");


        jLabel11.setText("Ort");

        javax.swing.GroupLayout paneCompanyLayout = new javax.swing.GroupLayout(paneCompany);
        paneCompany.setLayout(paneCompanyLayout);
        paneCompanyLayout.setHorizontalGroup(
            paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddCompany)
                .addContainerGap())
            .addGroup(paneCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        paneCompanyLayout.setVerticalGroup(
            paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btAddCompany)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Unternehmen", paneCompany);

        btAddMarket.setText("AddData");
        btAddMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddMarketActionPerformed(evt);
            }
        });

        jLabel12.setText("Name");

        jLabel13.setText("Ort");


        javax.swing.GroupLayout paneMarketLayout = new javax.swing.GroupLayout(paneMarket);
        paneMarket.setLayout(paneMarketLayout);
        paneMarketLayout.setHorizontalGroup(
            paneMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMarketLayout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addComponent(btAddMarket)
                .addContainerGap())
            .addGroup(paneMarketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMarketLayout.setVerticalGroup(
            paneMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMarketLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(paneMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbMPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btAddMarket)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Markt", paneMarket);

        panePlace.setToolTipText("");
        panePlace.setMaximumSize(new java.awt.Dimension(521, 204));
        panePlace.setMinimumSize(new java.awt.Dimension(521, 204));
        panePlace.setPreferredSize(new java.awt.Dimension(521, 204));

        btAddPlace.setText("AddData");
        btAddPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPlaceActionPerformed(evt);
            }
        });

        jLabel14.setText("Straße");

        jLabel15.setText("PLZ");

        jLabel16.setText("Stadt");

        javax.swing.GroupLayout panePlaceLayout = new javax.swing.GroupLayout(panePlace);
        panePlace.setLayout(panePlaceLayout);
        panePlaceLayout.setHorizontalGroup(
            panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePlaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePlaceLayout.createSequentialGroup()
                        .addGap(0, 402, Short.MAX_VALUE)
                        .addComponent(btAddPlace))
                    .addGroup(panePlaceLayout.createSequentialGroup()
                        .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panePlaceLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panePlaceLayout.createSequentialGroup()
                                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(21, 21, 21)
                                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPlCity, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panePlaceLayout.setVerticalGroup(
            panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePlaceLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panePlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddPlace)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Ort", panePlace);

        jTabbedPane1.addTab("Daten hinzufügen", jTabbedPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Suche");

        btnSearch.setText("Los!!");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchTerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchString = txtSearchTerm.getText();
        
        if(!"".equals(searchString))
        {
            //suchen alta
        }
       
        DefaultTableModel model = (DefaultTableModel) tblProductCompare.getModel();
      
        ArrayList<Product> productlist = new ArrayList<Product>();
        productlist.add(new Product(UUID.randomUUID(),"test1"));
        productlist.add(new Product(UUID.randomUUID(),"test2"));
        productlist.add(new Product(UUID.randomUUID(),"test3"));
                
        for(Product product : productlist)
        {
            model.addRow(new Object[]{product.getID(), product.getDescription(),product.getProductNumber(),"Preis",product.getMarket()});
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCompareProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareProductActionPerformed
        int[] Selection = tblProductCompare.getSelectedRows();
        
        UUID SelectedId1;
        UUID SelectedId2;
        if(Selection.length == 2){
            SelectedId1 = UUID.fromString(String.valueOf(tblProductCompare.getModel().getValueAt(Selection[0], 0)));
            SelectedId2 = UUID.fromString(String.valueOf(tblProductCompare.getModel().getValueAt(Selection[1], 0)));
        }
        
    }//GEN-LAST:event_btnCompareProductActionPerformed

    private void btAddProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductTypeActionPerformed
        ProductType pt = new ProductType();
        pt.setName(txtPtName.getText());
        db.Save(ProductType.class, pt);
    }//GEN-LAST:event_btAddProductTypeActionPerformed

    private void btAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCompanyActionPerformed
        Company company = new Company();
        company.setName(txtCName.getText());
        company.setPlace((Place)cbCPlace.getSelectedItem());
        db.Save(Company.class, company);
    }//GEN-LAST:event_btAddCompanyActionPerformed

    private void btAddMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddMarketActionPerformed
        Market market = new Market();
        market.setName(txtMName.getText());
        market.setPlace((Place)cbMPlace.getSelectedItem());
        db.Save(Market.class, market);
    }//GEN-LAST:event_btAddMarketActionPerformed

    private void btAddPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPlaceActionPerformed
        Place place = new Place();
        place.setStreet(txtPlStreet.getText());
        place.setCity(txtPlCity.getText());
        place.setZipCode(txtPlPLZ.getText());
        db.Save(Place.class, place);
    }//GEN-LAST:event_btAddPlaceActionPerformed

    private void btAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductActionPerformed
        Product product = new Product();
        product.setAmount(Double.parseDouble(txtPrAmount.getText()));
        product.setCompany((Company)cbPrCompany.getSelectedItem());
        product.setMarket((Market)cbPrMarket.getSelectedItem());
        product.setProductNumber(txtPrProductNumber.getText());
        product.setDescription(txtPaneDescription.getText());
        db.Save(Product.class, product);
    }//GEN-LAST:event_btAddProductActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        if (paneProduct.isShowing()) {}
        updateCBs();
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void cbPrMarketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPrMarketItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrMarketItemStateChanged

    private void cbPrCompanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPrCompanyItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrCompanyItemStateChanged

    private void jTabbedPane2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane2FocusGained
        updateCBs();
    }//GEN-LAST:event_jTabbedPane2FocusGained

    public void updateCBs()
    {
        for (Market market : Markets)
            cbPrMarket.addItem(market);
        for (Company company : Companies)
            cbPrCompany.addItem(company);
        for (ProductType producType : ProductTypes)
            cbPrProductType.addItem(producType);
        for (Place place : Places)
        {
            cbCPlace.addItem(place);
            cbMPlace.addItem(place);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AngebotsvergleichGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AngebotsvergleichGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AngebotsvergleichGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AngebotsvergleichGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AngebotsvergleichGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCompany;
    private javax.swing.JButton btAddMarket;
    private javax.swing.JButton btAddPlace;
    private javax.swing.JButton btAddProduct;
    private javax.swing.JButton btAddProductType;
    private javax.swing.JButton btnCompareProduct;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Place> cbCPlace;
    private javax.swing.JComboBox<Place> cbMPlace;
    private javax.swing.JComboBox<Company> cbPrCompany;
    private javax.swing.JComboBox<Market> cbPrMarket;
    private javax.swing.JComboBox<ProductType> cbPrProductType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel paneCompany;
    private javax.swing.JPanel paneMarket;
    private javax.swing.JPanel panePlace;
    private javax.swing.JPanel paneProduct;
    private javax.swing.JPanel paneProductType;
    private javax.swing.JTable tblProductCompare;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextArea txtPaneDescription;
    private javax.swing.JTextField txtPlCity;
    private javax.swing.JTextField txtPlPLZ;
    private javax.swing.JTextField txtPlStreet;
    private javax.swing.JTextField txtPrAmount;
    private javax.swing.JTextField txtPrProductNumber;
    private javax.swing.JTextField txtPtName;
    private javax.swing.JTextField txtSearchTerm;
    // End of variables declaration//GEN-END:variables
}
